# --- PROMETHEUS SERVICE ---
apiVersion: v1
kind: Service
metadata:
  name: prometheus
spec:
  ports:
    - port: 9090
      targetPort: 9090
  selector:
    app: prometheus
  type: ClusterIP  # Internal access only (Grafana talks to this)

---
# --- PROMETHEUS DEPLOYMENT ---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: prometheus
spec:
  replicas: 1
  selector:
    matchLabels:
      app: prometheus
  template:
    metadata:
      labels:
        app: prometheus
    spec:
      containers:
      - name: prometheus
        image: prom/prometheus:latest
        args:
          - "--config.file=/etc/prometheus/prometheus.yml"
          - "--storage.tsdb.retention.time=200h"
        ports:
        - containerPort: 9090
        volumeMounts:
        # Mount the config file we uploaded
        - name: config-volume
          mountPath: /etc/prometheus/prometheus.yml
          subPath: prometheus.yml
        # Mount data storage (Temporary for now)
        - name: data-volume
          mountPath: /prometheus
      volumes:
      - name: config-volume
        configMap:
          name: prometheus-config
      - name: data-volume
        emptyDir: {} # WARNING: Data is lost if pod restarts. Use PVC for persistence.

---
# --- GRAFANA SERVICE ---
apiVersion: v1
kind: Service
metadata:
  name: grafana
spec:
  ports:
    - port: 80
      targetPort: 3000
  selector:
    app: grafana
  type: LoadBalancer # Creates a Public IP to view dashboards

---
# --- GRAFANA DEPLOYMENT ---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: grafana
spec:
  replicas: 1
  selector:
    matchLabels:
      app: grafana
  template:
    metadata:
      labels:
        app: grafana
    spec:
      containers:
      - name: grafana
        image: grafana/grafana:latest
        ports:
        - containerPort: 3000
        env:
        - name: GF_SECURITY_ADMIN_USER
          value: "admin"
        - name: GF_SECURITY_ADMIN_PASSWORD
          value: "admin123"
        volumeMounts:
        - name: grafana-storage
          mountPath: /var/lib/grafana
        # --- Provisioning Files (Mapped to subdirectories) ---
        - name: grafana-provisioning
          mountPath: /etc/grafana/provisioning/datasources/prometheus.yml
          subPath: prometheus-ds
        - name: grafana-provisioning
          mountPath: /etc/grafana/provisioning/alerting/contact-points.yml
          subPath: contact-points
        - name: grafana-provisioning
          mountPath: /etc/grafana/provisioning/alerting/alert-rules.yml
          subPath: alerting-rules
        - name: grafana-provisioning
          mountPath: /etc/grafana/provisioning/alerting/policies.yml
          subPath: policies
        - name: grafana-provisioning
          mountPath: /etc/grafana/provisioning/dashboards/dashboard.yml
          subPath: dashboard-provider
        # --- JSON Dashboard ---
        - name: grafana-dashboards
          mountPath: /var/lib/grafana/dashboards/app-monitoring.json
          subPath: app-monitoring.json
      volumes:
      - name: grafana-storage
        emptyDir: {} # Use PVC for real production data
      - name: grafana-provisioning
        configMap:
          name: grafana-provisioning
      - name: grafana-dashboards
        configMap:
          name: grafana-dashboards