{
 "title": "FastAPI Monitoring",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Rate of Endpoint calls",
   "type": "timeseries",
   "description": "Frequency per second of specific endpoint calls over the last 5 minutes",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "sum by (endpoint) (rate(http_requests_total{endpoint=~\"/buy.*|/buy_random_deny.*|/concerts.*|/health|/metrics\"}[5m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Response Time (Latency)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 9, "x": 6, "y": 0 },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, rate(request_duration_seconds_bucket[1m]))",
     "legendFormat": "95th percentile"
    },
    {
     "expr": "histogram_quantile(0.50, rate(request_duration_seconds_bucket[1m]))",
     "legendFormat": "50th percentile"
    }
   ]
  },
  {
   "title": "Memory Usage (%)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 9, "x": 15, "y": 0 },
   "targets": [
    { "expr": "memory_usage_percent", "legendFormat": "Memory %" }
   ]
  },
  {
   "title": "Request Rate (req/s)",
   "type": "stat",
   "gridPos": { "h": 8, "w": 7, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "rate(http_requests_total[1m])", "legendFormat": "req/s" }
   ]
  },
  {
   "title": "CPU Usage (%)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 7, "y": 8 },
   "targets": [
    { "expr": "cpu_usage_percent", "legendFormat": "CPU %" }
   ]
  },
  {
   "title": "FastAPI Failure Rate (%)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 9, "x": 15, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "sum(rate(http_requests_total{status=~\"4..\"}[5m])) / sum(rate(http_requests_total[5m])) * 100",
     "legendFormat": "Server Errors (4xx)"
    }
   ]
  }
 ]
}